# Generated by Django 4.1.7 on 2023-03-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
